// export default function History({ history, onClear, onNavigate }) {
//   return (
//     <div className="page">
//       <div className="page-header">
//         <div>
//           <p className="page-eyebrow">Records</p>
//           <h2 className="page-title">Forecast history</h2>
//         </div>
//         {history.length > 0 && (
//           <button className="text-btn danger" onClick={onClear}>
//             Clear history
//           </button>
//         )}
//       </div>

//       {history.length === 0 && (
//         <div className="panel">
//           <div className="empty-block">
//             <p>No forecasts recorded on this device yet.</p>
//             <button className="primary-btn" onClick={() => onNavigate("forecast")}>
//               Run a forecast
//             </button>
//           </div>
//         </div>
//       )}

//       {history.length > 0 && (
//         <div className="panel table-panel">
//           <table className="history-table">
//             <thead>
//               <tr>
//                 <th>When</th>
//                 <th>Meals</th>
//                 <th>Staff</th>
//                 <th>Day</th>
//                 <th>Event</th>
//                 <th>Category</th>
//                 <th>Experience</th>
//                 <th className="align-right">Predicted</th>
//               </tr>
//             </thead>
//             <tbody>
//               {history.map((entry) => (
//                 <tr key={entry.id}>
//                   <td className="muted">
//                     {new Date(entry.timestamp).toLocaleDateString(undefined, {
//                       month: "short",
//                       day: "numeric",
//                     })}{" "}
//                     <span className="muted-light">
//                       {new Date(entry.timestamp).toLocaleTimeString(undefined, {
//                         hour: "2-digit",
//                         minute: "2-digit",
//                       })}
//                     </span>
//                   </td>
//                   <td>{entry.input.meals_served}</td>
//                   <td>{entry.input.kitchen_staff}</td>
//                   <td>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][entry.input.day_of_week]}</td>
//                   <td>{entry.input.special_event === 1 ? "Yes" : "—"}</td>
//                   <td className="capitalize">{entry.input.waste_category}</td>
//                   <td className="capitalize">{entry.input.staff_experience}</td>
//                   <td className="align-right strong">{entry.predictedKg.toFixed(1)} kg</td>
//                 </tr>
//               ))}
//             </tbody>
//           </table>
//         </div>
//       )}
//     </div>
//   );
// }


function getDay(value) {
  return ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][value];
}

function getLevel(kg) {
  if (kg < 30) return "low";
  if (kg < 60) return "moderate";
  return "high";
}

export default function History({
  history,
  onClear,
  onNavigate,
}) {
  return (
    <div className="page">
      <div className="page-header">
        <div>
          <span className="page-eyebrow">YOUR RECORDS</span>
          <h1 className="page-title">Forecast history</h1>
          <p className="page-subtitle">
            Review the predictions generated by WasteWise AI.
          </p>
        </div>

        {history.length > 0 && (
          <button className="danger-btn" onClick={onClear}>
            <span>⌫</span>
            Clear history
          </button>
        )}
      </div>

      {history.length === 0 && (
        <div className="empty-history">
          <div className="history-empty-icon">
            <svg viewBox="0 0 24 24" fill="none">
              <circle cx="12" cy="12" r="8.5" />
              <path d="M12 7v5l3 2" />
            </svg>
          </div>

          <span className="panel-kicker">NO RECORDS YET</span>

          <h2>Your forecast history is empty</h2>

          <p>
            Once you create predictions, they will appear here
            so you can compare your cafeteria's waste patterns.
          </p>

          <button
            className="primary-btn"
            onClick={() => onNavigate("forecast")}
          >
            Create a forecast →
          </button>
        </div>
      )}

      {history.length > 0 && (
        <>
          <div className="history-summary">
            <div>
              <span>Total forecasts</span>
              <strong>{history.length}</strong>
            </div>

            <div>
              <span>Average waste</span>
              <strong>
                {(
                  history.reduce(
                    (sum, item) => sum + item.predictedKg,
                    0
                  ) / history.length
                ).toFixed(1)}{" "}
                kg
              </strong>
            </div>

            <div>
              <span>Latest prediction</span>
              <strong>{history[0].predictedKg.toFixed(1)} kg</strong>
            </div>
          </div>

          <div className="panel table-panel">
            <div className="table-heading">
              <div>
                <span className="panel-kicker">PREDICTION LOG</span>
                <h3>All forecasts</h3>
              </div>

              <span className="record-count">
                {history.length} records
              </span>
            </div>

            <div className="table-scroll">
              <table className="history-table">
                <thead>
                  <tr>
                    <th>Forecast</th>
                    <th>Service</th>
                    <th>Conditions</th>
                    <th>Category</th>
                    <th>Experience</th>
                    <th className="align-right">Prediction</th>
                  </tr>
                </thead>

                <tbody>
                  {history.map((entry, index) => {
                    const level = getLevel(entry.predictedKg);

                    return (
                      <tr
                        key={entry.id}
                        style={{
                          animationDelay: `${index * 45}ms`,
                        }}
                      >
                        <td>
                          <div className="date-cell">
                            <strong>
                              {new Date(
                                entry.timestamp
                              ).toLocaleDateString(undefined, {
                                month: "short",
                                day: "numeric",
                              })}
                            </strong>

                            <span>
                              {new Date(
                                entry.timestamp
                              ).toLocaleTimeString(undefined, {
                                hour: "2-digit",
                                minute: "2-digit",
                              })}
                            </span>
                          </div>
                        </td>

                        <td>
                          <div className="service-cell">
                            <strong>
                              {entry.input.meals_served}
                            </strong>
                            <span>meals</span>
                            <small>
                              {entry.input.kitchen_staff} staff
                            </small>
                          </div>
                        </td>

                        <td>
                          <div className="condition-cell">
                            <span>
                              {getDay(entry.input.day_of_week)}
                            </span>
                            <span>
                              {entry.input.temperature_C}°C
                            </span>
                            {entry.input.special_event === 1 && (
                              <b>Event</b>
                            )}
                          </div>
                        </td>

                        <td>
                          <span className="category-badge capitalize">
                            {entry.input.waste_category}
                          </span>
                        </td>

                        <td className="capitalize">
                          {entry.input.staff_experience}
                        </td>

                        <td className="align-right">
                          <div className="prediction-cell">
                            <strong>
                              {entry.predictedKg.toFixed(1)} kg
                            </strong>
                            <span className={`level-dot ${level}`} />
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}
    </div>
  );
}